# Generated by Django 5.1.6 on 2025-05-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('horror', 'Horror'), ('action', 'Action'), ('Fantansy', 'Fantasy'), ('romance', 'Romance')], max_length=100)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
