# Generated by Django 5.1.6 on 2025-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='default.png', upload_to='covers/')),
                ('title', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField()),
                ('genre', models.CharField(choices=[('horror', 'Horror'), ('action', 'Action'), ('Fantansy', 'Fantasy'), ('romance', 'Romance')], max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
