# Generated by Django 5.1.6 on 2025-05-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/default.jpg', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
