# Generated by Django 5.1.6 on 2025-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_book_cover_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='covers/default.jpg', upload_to='covers/')),
                ('title', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField()),
                ('genre', models.CharField(choices=[('horror', 'Horror'), ('action', 'Action'), ('Fantansy', 'Fantasy'), ('romance', 'Romance')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
