# Generated by Django 5.1.6 on 2025-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_bigbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='dedication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
